name: CrownConquest
main: me.lucasemanuel.crownconquest.Main
version: 1.5
depend: [WorldGuard, WorldEdit]

commands:
  start:
    description: Starts the 2 minute countdown.
    usage: /<command>
    permission: crownconquest.commands.start
  stopcq:
    description: Stops the game.
    usage: /<command>
    permission: crownconquest.commands.stopcq
  setcrownspawn:
    description: Adds crown spawnpoint.
    usage: /<command>
    permission: crownconquest.commands.setcrownspawn
  setteamspawn:
    description: Adds a spawnpoint for a team.
    usage: /<command> <teamname>
    permission: crownconquest.commands.setteamspawn
  spawncrown:
    description: Spawns a crown at a random preset location.
    usage: /<command>
    permission: crownconquest.commands.spawncrown
  teams:
    description: Prints the names of the teams and their members.
    usage: /<command>
    permission: crownconquest.commands.teams
  setspectatorspawn:
    description: Sets the place dead players will spawn in.
    usage: /<command>
    permission: crownconquest.commands.setspectatorspawn
    
    
permissions:
  crownconquest.signs.registerteamsign:
    description: Allows a player to register a sign that allows players to join teams.
    default: op